Pulu\PalstaBundle\Entity\ArticleLocalization:
    type: entity
    table: article_localization
    id:
        article:
            type: integer
            associationKey: true
        language:
            type: string
            length: 2
    fields:
        name:
            type: string
            length: 256
        teaser:
            type: text
            length: 1024
            nullable: true
    manyToOne:
        article:
            targetEntity: Article
            inversedBy: localizations