Pulu\PalstaBundle\Entity\ArticleLocalization:
    type: entity
    table: article_localization
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        language:
            type: string
            length: 2
        name:
            type: string
            length: 256
        teaser:
            type: text
            length: 1024
            nullable: true
    manyToOne:
        article:
            targetEntity: Article
            inversedBy: localizations
            joinColumn:
                name: article_id
                referencedColumnName: id
                nullable: false
                onDelete: cascade
    uniqueConstraints:
        article_language_un:
            columns: [article_id, language]