Pulu\PalstaBundle\Entity\Article:
    type: entity
    table: article
    repositoryClass: Pulu\PalstaBundle\Entity\ArticleRepository
    id:
        id:
            type: integer
            generator:
                strategy: sequence
            sequenceGenerator:
                sequenceName: article_id_seq
                allocationSize: 10
                initialValue: 1
    fields:
        article_number:
            type: integer
            unique: true
        type:
            type: integer
            nullable: true
        created:
            type: datetime
        modified:
            type: datetime
        modified_public:
            type: datetime
            nullable: true
        published:
            type: datetime
        written_at:
            type: text
            nullable: true
        deleted:
            type: datetime
            nullable: true
        rating:
            type: decimal
            precision: 10
            scale: 2
            nullable: true
        visits:
            type: integer
        old_visits:
            type: integer
            nullable: true
        last_month_visits:
            type: integer
            nullable: true
        average_monthly_visits:
            type: decimal
            precision: 10
            scale: 2
            nullable: true
        is_one_of_best:
            type: boolean
            nullable: true
        is_commentable:
            type: boolean
            nullable: true
        use_translator:
            type: boolean
            nullable: true
        language:
            type: string
            length: 2
            nullable: true
        is_public:
            type: boolean
            nullable: true
        access:
            type: integer
            nullable: true
    lifecycleCallbacks:
        prePersist: [ setCreated, setModified ]
    oneToMany:
        localizations:
            targetEntity: ArticleLocalization
            mappedBy: article
            cascade: [ persist ]
        revisions:
            targetEntity: ArticleRevision
            mappedBy: article
            cascade: [ persist ]
        comments:
            targetEntity: Comment
            mappedBy: article
            cascade: [ persist ]
        keywords:
            targetEntity: ArticleKeyword
            mappedBy: article
            cascade: [ persist ]
        raw_visits:
            targetEntity: Visit
            mappedBy: article
            cascade: [ persist ]
        raw_ratings:
            targetEntity: Rating
            mappedBy: article
            cascade: [ persist ]
        modules:
            targetEntity: Module
            mappedBy: article
            cascade: [ persist ]
