Pulu\PalstaBundle\Entity\Article:
    type: entity
    table: article
    id:
        id:
            type: integer
            generator:
                strategy: sequence
            sequenceGenerator:
                sequenceName: article_seq
                allocationSize: 10
                initialValue: 1
    fields:
        created:
            type: datetime
        modified:
            type: datetime
        deleted:
            type: datetime
            nullable: true
        points:
            type: integer
        visits:
            type: integer
    lifecycleCallbacks:
        prePersist: [ setCreated, setModified ]
        preUpdate: [ setModified ]
    oneToMany:
        localizations:
            targetEntity: ArticleLocalization
            mappedBy: article
            cascade: ["persist"]