Pulu\PalstaBundle\Entity\ArticleKeyword:
    type: entity
    table: article_keyword
    id:
        id:
            type: integer
            generator:
                strategy: sequence
            sequenceGenerator:
                sequenceName: article_keyword_id_seq
                allocationSize: 10
                initialValue: 1
    fields:
        weight:
            type: decimal
            precision: 10
            scale: 3
            nullable: true
    manyToOne:
        article:
            targetEntity: Article
            inversedBy: keywords
        keyword:
            targetEntity: Keyword
            inversedBy: articles