Pulu\PalstaBundle\Entity\Keyword:
    type: entity
    table: keyword
    repositoryClass: Pulu\PalstaBundle\Entity\KeywordRepository
    id:
        id:
            type: integer
            generator:
                strategy: sequence
            sequenceGenerator:
                sequenceName: keyword_id_seq
                allocationSize: 10
                initialValue: 1
    fields:
        weight:
            type: decimal
            precision: 10
            scale: 3
            nullable: true
        created:
            type: datetime
        modified:
            type: datetime
        deleted:
            type: datetime
            nullable: true
    lifecycleCallbacks:
        prePersist: [ setCreated, setModified ]
        preUpdate: [ setModified ]
    oneToMany:
        localizations:
            targetEntity: KeywordLocalization
            mappedBy: keyword
            cascade: ["persist"]
        articles:
            targetEntity: ArticleKeyword
            mappedBy: keyword
            cascade: ["persist"]