Pulu\PalstaBundle\Entity\KeywordLocalization:
    type: entity
    table: keyword_localization
    id:
        keyword:
            type: integer
            associationKey: true
        language:
            type: string
            length: 2
    fields:
        name:
            type: string
            length: 256
    manyToOne:
        keyword:
            targetEntity: Keyword
            inversedBy: localizations