Pulu\PalstaBundle\Entity\Tag:
    type: entity
    table: tag
    repositoryClass: Pulu\PalstaBundle\Entity\TagRepository
    id:
        id:
            type: integer
            generator:
                strategy: sequence
            sequenceGenerator:
                sequenceName: tag_id_seq
                allocationSize: 10
                initialValue: 1
    fields:
        weight:
            type: decimal
            precision: 10
            scale: 3
            nullable: true
        created:
            type: datetime
        modified:
            type: datetime
        deleted:
            type: datetime
            nullable: true
    lifecycleCallbacks:
        prePersist: [ setCreated, setModified ]
        preUpdate: [ setModified ]
    oneToMany:
        localizations:
            targetEntity: TagLocalization
            mappedBy: tag
            cascade: ["persist"]
        articles:
            targetEntity: ArticleTag
            mappedBy: tag
            cascade: ["persist"]