pulu_palsta_front:
    pattern: /
    defaults: { _controller: PuluPalstaBundle:Front:index}

pulu_palsta_article_create:
    pattern: /article/create/{name}
    defaults: { _controller: PuluPalstaBundle:Article:create, name = 'Test name' }

pulu_palsta_article_list:
    pattern: /article
    defaults: { _controller: PuluPalstaBundle:Article:index }

pulu_palsta_about:
    pattern: /tietoa
    defaults: { _controller: PuluPalstaBundle:About:index }