pulu_palsta_root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /fi
        permanent: true

pulu_palsta_login:
    pattern: /login
    defaults: {_controller: PuluPalstaBundle:Login:login}

pulu_palsta_login_check:
    pattern: /login_check

pulu_palsta_logout:
    pattern: /logout

pulu_palsta_front:
    pattern: /{_locale}
    defaults: { _controller: PuluPalstaBundle:Front:index}
    requirements:
        _locale: fi|en

pulu_palsta_about:
    pattern: /{_locale}/tietoa
    defaults: { _controller: PuluPalstaBundle:About:index }
    requirements:
        _locale: fi|en

pulu_palsta_list:
    pattern: /{_locale}/luettelo
    defaults: { _controller: PuluPalstaBundle:List:index }
    requirements:
        _locale: fi|en

pulu_palsta_article_without_name:
    pattern: /{_locale}/{id}
    defaults: { _controller: PuluPalstaBundle:Article:redirect }
    requirements:
        id: \d+
        _locale: fi|en

pulu_palsta_article:
    pattern: /{_locale}/{id}-{name}
    defaults: { _controller: PuluPalstaBundle:Article:view, id: 1, name: default }
    requirements:
        id: \d+
        name: ([A-Za-z0-9-]+)
        _locale: fi|en

##### ADMIN #####
pulu_palsta_admin:
    pattern: /admin
    defaults: { _controller: PuluPalstaBundle:Admin:index }

pulu_palsta_admin_article:
    pattern: /admin/article
    defaults: { _controller: PuluPalstaBundle:Admin:listArticle }

pulu_palsta_admin_article_create:
    pattern: /admin/article/create
    defaults: { _controller: PuluPalstaBundle:Admin:handleArticle }

pulu_palsta_admin_article_edit:
    pattern: /admin/article/edit/{id}
    defaults: { _controller: PuluPalstaBundle:Admin:handleArticle }
    requirements:
        id: \d+

pulu_palsta_admin_article_delete:
    pattern: /admin/article/delete/{id}
    defaults: { _controller: PuluPalstaBundle:Admin:handleArticle }
    requirements:
        id: \d+

pulu_palsta_admin_keyword:
    pattern: /admin/keyword
    defaults: { _controller: PuluPalstaBundle:Admin:listKeyword }

pulu_palsta_admin_keyword_create:
    pattern: /admin/keyword/create
    defaults: { _controller: PuluPalstaBundle:Admin:handleKeyword }

pulu_palsta_admin_keyword_edit:
    pattern: /admin/keyword/edit/{id}
    defaults: { _controller: PuluPalstaBundle:Admin:handleKeyword }
    requirements:
        id: \d+

pulu_palsta_admin_keyword_delete:
    pattern: /admin/keyword/delete/{id}
    defaults: { _controller: PuluPalstaBundle:Admin:handleKeyword }
    requirements:
        id: \d+

pulu_palsta_admin_comment:
    pattern: /admin/comment
    defaults: { _controller: PuluPalstaBundle:Admin:listComment }

pulu_palsta_admin_comment_edit:
    pattern: /admin/comment/edit/{id}
    defaults: { _controller: PuluPalstaBundle:Admin:handleComment }

pulu_palsta_admin_account:
    pattern: /admin/account
    defaults: { _controller: PuluPalstaBundle:Admin:account }

pulu_palsta_admin_setting:
    pattern: /admin/setting
    defaults: { _controller: PuluPalstaBundle:Admin:setting }