pulu_palsta_root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /fi
        permanent: true

pulu_palsta_login:
    path: /login
    defaults: {_controller: PuluPalstaBundle:Login:login}

pulu_palsta_login_check:
    path: /login_check

pulu_palsta_logout:
    path: /logout

pulu_palsta_front:
    path: /{_locale}
    defaults: { _controller: PuluPalstaBundle:Front:index}
    requirements:
        _locale: fi|en

pulu_palsta_front_with_trailing_slash:
    path: /{_locale}/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: pulu_palsta_front
        permanent: true
    requirements:
        _locale: fi|en

pulu_palsta_about:
    path: /{_locale}/about
    defaults: { _controller: PuluPalstaBundle:About:index }
    requirements:
        _locale: fi|en

pulu_palsta_list:
    path: /{_locale}/table-of-contents
    defaults: { _controller: PuluPalstaBundle:List:index }
    requirements:
        _locale: fi|en

pulu_palsta_index:
    path: /{_locale}/index
    defaults: { _controller: PuluPalstaBundle:Index:index }
    requirements:
        _locale: fi|en

pulu_palsta_article_without_name:
    path: /{_locale}/{article_number}
    defaults: { _controller: PuluPalstaBundle:Article:redirect }
    requirements:
        article_number: \d+
        _locale: fi|en

pulu_palsta_article:
    path: /{_locale}/{article_number}-{name}
    defaults: { _controller: PuluPalstaBundle:Article:view, article_number: 1, name: default }
    options:
        expose: true
    requirements:
        article_number: \d+
        name: ([A-Za-z0-9-]+)
        _locale: fi|en

pulu_palsta_article_rating:
    path: /{_locale}/ajax/rating
    defaults: { _controller: PuluPalstaBundle:Ajax:articleRating }
    options:
        expose: true
    requirements:
        _locale: fi|en

pulu_palsta_article_comment:
    path: /{_locale}/ajax/comment
    defaults: { _controller: PuluPalstaBundle:Ajax:articleComment }
    options:
        expose: true
    requirements:
        _locale: fi|en

pulu_palsta_keyword:
    path: /{_locale}/ajax/keyword
    defaults: { _controller: PuluPalstaBundle:Ajax:keyword }
    options:
        expose: true
    requirements:
        _locale: fi|en

pulu_palsta_feed_recent_articles:
    path: /{_locale}/feed/recent_articles
    defaults: { _controller: PuluPalstaBundle:Feed:recentArticles }
    requirements:
        _locale: fi|en

pulu_palsta_feed_recent_comments:
    path: /{_locale}/feed/recent_comments
    defaults: { _controller: PuluPalstaBundle:Feed:recentComments }
    requirements:
        _locale: fi|en

##### ADMIN #####
pulu_palsta_admin:
    path: /admin
    defaults: { _controller: PuluPalstaBundle:Admin:index }

pulu_palsta_admin_article:
    path: /admin/article
    defaults: { _controller: PuluPalstaBundle:Admin:listArticle }

pulu_palsta_admin_article_create:
    path: /admin/article/create
    defaults: { _controller: PuluPalstaBundle:Admin:handleArticle }

pulu_palsta_admin_article_edit:
    path: /admin/article/edit/{id}
    defaults: { _controller: PuluPalstaBundle:Admin:handleArticle }
    requirements:
        id: \d+

pulu_palsta_admin_article_delete:
    path: /admin/article/delete/{id}
    defaults: { _controller: PuluPalstaBundle:Admin:handleArticle }
    requirements:
        id: \d+

pulu_palsta_admin_article_history:
    path: /admin/article/history/{id}
    defaults: { _controller: PuluPalstaBundle:Admin:historyArticle }
    requirements:
        id: \d+

pulu_palsta_admin_article_diff:
    path: /admin/article/diff/{id}
    defaults: { _controller: PuluPalstaBundle:Admin:diffArticle }
    requirements:
        id: \d+
        revision: \d+

pulu_palsta_admin_keyword:
    path: /admin/keyword
    defaults: { _controller: PuluPalstaBundle:Admin:listKeyword }

pulu_palsta_admin_keyword_create:
    path: /admin/keyword/create
    defaults: { _controller: PuluPalstaBundle:Admin:handleKeyword }

pulu_palsta_admin_keyword_edit:
    path: /admin/keyword/edit/{id}
    defaults: { _controller: PuluPalstaBundle:Admin:handleKeyword }
    requirements:
        id: \d+

pulu_palsta_admin_keyword_delete:
    path: /admin/keyword/delete/{id}
    defaults: { _controller: PuluPalstaBundle:Admin:handleKeyword }
    requirements:
        id: \d+

pulu_palsta_admin_comment:
    path: /admin/comment
    defaults: { _controller: PuluPalstaBundle:Admin:listComment }

pulu_palsta_admin_comment_edit:
    path: /admin/comment/edit/{id}
    defaults: { _controller: PuluPalstaBundle:Admin:handleComment }
    requirements:
        id: \d+

pulu_palsta_admin_account:
    path: /admin/account
    defaults: { _controller: PuluPalstaBundle:Admin:account }

pulu_palsta_admin_setting:
    path: /admin/setting
    defaults: { _controller: PuluPalstaBundle:Admin:setting }

pulu_palsta_admin_guide:
    path: /admin/guide
    defaults: { _controller: PuluPalstaBundle:Admin:guide }

pulu_palsta_admin_module:
    path: /admin/module
    defaults: { _controller: PuluPalstaBundle:Module:index }

pulu_palsta_admin_module_create:
    path: /admin/module/create
    defaults: { _controller: PuluPalstaBundle:Module:handle }

pulu_palsta_admin_module_edit:
    path: /admin/module/edit/{id}
    defaults: { _controller: PuluPalstaBundle:Module:handle }
    requirements:
        id: \d+

pulu_palsta_admin_module_delete:
    path: /admin/module/delete/{id}
    defaults: { _controller: PuluPalstaBundle:Module:handle }
    requirements:
        id: \d+

pulu_palsta_admin_module_use:
    path: /admin/module/use/{id}
    defaults: { _controller: PuluPalstaBundle:Module:use }
    options:
        expose: true
    requirements:
        id: \d+

pulu_palsta_admin_api_visit:
    path: /admin/api/visit
    defaults: { _controller: PuluPalstaBundle:Api:getVisit }

pulu_palsta_admin_visit:
    path: /admin/visit
    defaults: { _controller: PuluPalstaBundle:Admin:visit }

pulu_palsta_admin_visit_average:
    path: /admin/visit/average
    defaults: { _controller: PuluPalstaBundle:Admin:visitAverage }
