services:
    helper:
        class: Pulu\PalstaBundle\DependencyInjection\Helper
        tags:
                - { name: templating.helper, alias: helper }
    article_manager:
        class: Pulu\PalstaBundle\Manager\ArticleManager
        arguments: ["article"]