Pulu\PalstaBundle\Entity\Article:
    properties:
        visits:
            - Min: 0
            - Max: 1000000000

        rating:
            - Min: 0
            - Max: 1000

Pulu\PalstaBundle\Entity\ArticleLocalization:
    properties:
        name:
            - NotNull: { message: "article.name.not_blank" }